name: Build
on:
 pull_request:
   branches:
     - main
jobs:
  deploy-heroku:
    runs-on: ubuntu-latest
    name: heroku deploy
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "alectrion-front"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            GATEWAY_URL
        env:
          GATEWAY_URL: ${{ secrets.GATEWAY_URL }}